### ISSUE TITLE
Worker update always fails in Google Colab notebooks

### ISSUE THREAD

**Issue by MinetaS** [official-stockfish/fishtest#2395]
```
Exception while updating to version 297:
'module' object has no attribute 'colab'
Attempted update to worker version 297 failed!
```

This also happened when updating from 295 to 296.

**Comment by vdbergh** [comment]
I don't understand 100% what goes on but what happens is

1)`worker.py` imports `updater.py::update()`
2) `worker.py` tries to import `google.colab` and deletes it again on success. In that case `IS_COLAB` is set to `True`.
3) `worker.py` calls `updater.py::update()`
4) `update.py::update()` tries to import `worker.py::verify_sri()`. 
5) This causes Python to try to delete `google.colab` again, which does not work.

**Comment by MinetaS** [comment]
So this is what I think:

1. When `import google.colab` is executed, both `google` and `google.colab` is defined as a module respectively.
2. Now, when doing the second import after `del google.colab`, the module is already in `sys.modules` and returns that module without the parent attribute binding.
3. `google.colab` is imported but `colab` attribute itself is missing in `google`, because it is deleted. Hence raises `AttributeError` at the second `del`.
